User:
  actAs: [Timestampable]
  tableName: do_auth_user
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    username:
      type: string(128)
      notnull: true
      unique: true
    email:
      type: string(128)
      notnull: false
      unique: true
    salt: string(128)
    password: string(128)
    is_active:
      type: boolean
      default: 0
    is_super_admin:
      type: boolean
      default: false
    last_login:
      type: timestamp
  indexes:
    name_idx:
      fields: [username]
      unique: true

UserActivationCode:
  actAs: [Timestampable]
  tableName: do_auth_user_activation_code
  options:
    symfony:
      form:   false
      filter: false
  columns:
    user_id:
      type: integer
      primary: true
    code:
      type: string(128)
  relations:
    User:
      class: User
      foreign: id
      local: user_id
      type: one
      onDelete: cascade
